name: Deploy to EC2

on:
#   push:
#     branches:
#       - main
#       - feature/deploy
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker compose build

    - name: Push Docker Image
      run: |
        docker push seohyun7/melodiary:latest

    - name: Add SSH Key
      run: |
        echo "${{ secrets.EC2_KEY }}" | base64 -d > desktop.pem
        chmod 600 desktop.pem

    - name: Deploy on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i desktop.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          sudo docker pull seohyun7/melodiary:latest
          sudo docker stop melodiary || true
          sudo docker rm melodiary || true
          sudo docker run -d \
            -p 3001:3001 \
            --name melodiary \
            --env-file /home/ubuntu/.env \
            seohyun7/melodiary:latest
        EOF
